# Generated by ChatGPT for V5.2.17 hotfix: merge migration heads
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_fl'),
        ('core', '0011_add_volume_to_dailybar'),
    ]

    operations = []
