# Generated by Django 5.2.15 on 2026-07-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_regularize_historical_model_drift'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunConfigurationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('BACKTEST', 'Backtest'), ('GAME', 'Game')], db_index=True, max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('config_hash', models.CharField(db_index=True, max_length=64)),
                ('scenario_snapshot', models.JSONField(blank=True, default=dict)),
                ('run_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_backtest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_snapshots', to='core.backtest')),
                ('source_game_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_snapshots', to='core.gamescenario')),
                ('source_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_snapshots', to='core.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='core_runcon_kind_d513d9_idx'), models.Index(fields=['config_hash'], name='core_runcon_config__203064_idx'), models.Index(fields=['source_backtest'], name='core_runcon_source__9fc029_idx'), models.Index(fields=['source_game_scenario'], name='core_runcon_source__4ec032_idx')],
            },
        ),
    ]
