# Generated by Django 5.2.15 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_run_configuration_snapshots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="universe_mode",
            field=models.CharField(
                choices=[
                    ("STATIC_TICKERS", "Sélection statique de tickers"),
                    ("SP500_HISTORICAL_DYNAMIC", "S&P500 historique dynamique"),
                    ("CSI300_HISTORICAL_DYNAMIC", "CSI 300 historique dynamique — via CSV"),
                ],
                default="STATIC_TICKERS",
                help_text="Mode d'univers du scénario. Phase 1 stocke uniquement ce choix.",
                max_length=32,
            ),
        ),
    ]
